### PR TITLE
Upgrade rust edition to 2021 (#23)

### LINKED ISSUE #23: Upgrade rust edition and out of date dependencies
I was wondering if I could raise a PR to update the rust edition and also some of the dependencies?

- Rust edition 2018 -> 2021
- itertools `0.8` -> `0.10`
- time `0.1.44` -> perhaps remove it in place of chrono? Otherwise `0.3.9` if it is still required?

I noticed I cannot build it with the old edition (as mentioned in my note on https://github.com/rust-motd/rust-motd/issues/16#issuecomment-1158246075), but maybe that is my toolchain setup?

```
❯ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/nick/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.61.0 (fe5b13d68 2022-05-18)

```

### PR DESCRIPTION
**Pull request by NickLarsenNZ**
Closes #23

- Upgrade to the 2021 edition of Rust.
- Upgrade `itertools`.
- Remove `time`, it looks like chrono can do everything necessary - but I'm not sure, so perhaps it needs some more user testing.

### CODE REVIEW

**Comment by aaronscode** [comment]
@NickLarsenNZ - re-opening this PR because I've finally gotten a chance to look at it. Sorry about the delay. Your changes look good to me. Regarding `chrono` vs `time`, it looks like there was some debate because both were vulnerable to a [CVE](https://rustsec.org/advisories/RUSTSEC-2020-0071), `chrono` by way of `time` as a dependency, actually. The most recent version of `chrono` at the time of writing (0.4.22) has fixed this. @MarcelRobitaille, this vulnerability is still in our dependency chain by way of `utmp-rs`. Could you bump that version when you get a chance (I'll make an issue on that project)?

I checked all of this using `cargo-audit` and bumped a couple other crate versions to fix security vulnerabilities. I also gave `docker-api` a static version instead of pointing to a github repo. This version is one below the latest, but there are some breaking changes, so I'm comfortable leaving it there for now.

@MarcelRobitaille please take a look and let me know what you think. I'm good to merge if you're happy with the changes.

**Comment by MarcelRobitaille** [comment]
I've dealt with the `utmp-rs` issue, including using the main `utmp-rs` instead of my own fork. I also published `last-rs` to crates.io. I replaced `chrono` with `time` in `rust-motd` and `last-rs`. However, we still depend on `chrono` via `systemstat` and `docker-api`.

`cargo audit`:
```
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 452 security advisories (from /home/marcel/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (163 crate dependencies)
Crate:     time
Version:   0.1.44
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.44
└── chrono 0.4.22
    ├── systemstat 0.1.12
    │   └── rust-motd 0.3.0
    ├── rust-motd 0.3.0
    └── docker-api 0.9.2
        └── rust-motd 0.3.0

Crate:     ansi_term
Version:   0.12.1
Warning:   unmaintained
Title:     ansi_term is Unmaintained
Date:      2021-08-18
ID:        RUSTSEC-2021-0139
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0139
Dependency tree:
ansi_term 0.12.1
└── clap 2.34.0
    └── last-rs 0.2.1
        └── rust-motd 0.3.0

error: 1 vulnerability found!
warning: 1 allowed warning found
```

**Comment by MarcelRobitaille** [comment]
@aaronscode I'm ok with the changes as well. Should we merge or should we try to fix the remaining vulnerabilities and warnings? That seems to have taken over this pr.

**Comment by aaronscode** [comment]
Let's merge and handle those later

**Pull request merged**
