### PR TITLE
Add load_avg component

### PR DESCRIPTION
**Pull request by wentasah**
This prints a message like this:

    Load (1/5/15 min.): 0.40, 0.44, 0.62

### CODE REVIEW

**Comment by MarcelRobitaille** [comment]
Thanks for the contribution. I'm not sure about the formatting. I find it a bit odd that the prefix is configurable but not the data. What about making the entire line into a configurable format string? At the very least, I would not use slashes in the prefix and commas in the data.

**Comment by MarcelRobitaille** [comment]
There should be a change to the readme too.

**Comment by wentasah** [comment]
How about this? I made the whole line configurable using the `interpolator` crate, which seems both popular and lightweight.

**Comment by wentasah** [comment]
The last update was rebase to `main` for fix the conflict.

**Comment by MarcelRobitaille** [comment]
Looks good. Thanks for your efforts.

**Pull request merged**
